# autogenerated sources_list.cmakefor project(dummy_project)

set(GROUP_CORE_SRC
	        Core/Src/adc.c
		Core/Src/crc.c
		Core/Src/dma.c
		Core/Src/freertos.c
		Core/Src/gpio.c
		Core/Src/i2c.c
		Core/Src/iwdg.c
		Core/Src/main.c
		Core/Src/spi.c
		Core/Src/stm32f1xx_hal_msp.c
		Core/Src/stm32f1xx_hal_timebase_tim.c
		Core/Src/stm32f1xx_it.c
		Core/Src/system_stm32f1xx.c
		Core/Src/tim.c
		Core/Src/usart.c
		Core/Src/wwdg.c
		Core/Src/rtc.c
)

set(GROUP_CORE_SRC_DISPLAY
	        Core/Src/display/framebuffer.c
		Core/Src/display/ssd1306.c
)

set(GROUP_CORE_SRC_HELPERS
	        Core/Src/helpers/ascii_helpers.c
		Core/Src/helpers/crc32_helpers.c
		Core/Src/helpers/logging.c
		Core/Src/helpers/messages.c
		Core/Src/helpers/my_comm.c
		Core/Src/helpers/myCRT.c
		Core/Src/helpers/num_helpers.c
#		Core/Src/helpers/rtc_helpers.c
                Core/Src/helpers/watchdog.c
		Core/Src/helpers/xprintf.c
		Core/Src/helpers/hex_gen.c
		Core/Src/helpers/i2c_eeprom.c
		Core/Src/helpers/ftoa.c
		Core/Src/helpers/sys_helpers.c
)

set(GROUP_CORE_SRC_APP
	        Core/Src/app/comm_task.c
		Core/Src/app/control_task.c
		Core/Src/app/kbd_task.c
		Core/Src/app/temperatur_task.c
		Core/Src/app/ui_task.c
		Core/Src/app/startup.c
)

set(GROUP_CORE_SRC_BSP
	        Core/Src/bsp/exti.c
		Core/Src/bsp/temerature_measurement.c
		Core/Src/bsp/parameters_storage.c
		Core/Src/bsp/door_servo.c
)

set(GROUP_CORE_SRC_MENU
	        Core/Src/menu/menu.c
)

set(GROUP_CORE_SRC_PROFILES
	        Core/Src/profiles/profiles.c
		Core/Src/profiles/regulator.c
)


set(GROUP_DRIVERS_STM32F1XX_HAL_DRIVER_SRC
	        Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal.c
		Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_adc.c
		Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_adc_ex.c
		Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_cortex.c
		Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_crc.c
		Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_dma.c
		Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_flash.c
		Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_flash_ex.c
		Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_gpio.c
		Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_gpio_ex.c
		Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_i2c.c
		Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_iwdg.c
		Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_pwr.c
		Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_rcc.c
		Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_rcc_ex.c
		Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_spi.c
		Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_spi_ex.c
		Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_tim.c
		Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_tim_ex.c
		Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_uart.c
		Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_wwdg.c
		Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_rtc.c
		Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_rtc_ex.c
)

set(GROUP_MIDDLEWARES_THIRD_PARTY_FREERTOS_SOURCE_CMSIS_RTOS
	        Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS/cmsis_os.c
)

set(GROUP_MIDDLEWARES_THIRD_PARTY_FREERTOS_SOURCE_PORTABLE_GCC_ARM_CM3
	        Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM3/port.c
)

set(GROUP_MIDDLEWARES_THIRD_PARTY_FREERTOS_SOURCE
	        Middlewares/Third_Party/FreeRTOS/Source/croutine.c
		Middlewares/Third_Party/FreeRTOS/Source/event_groups.c
		Middlewares/Third_Party/FreeRTOS/Source/list.c
		Middlewares/Third_Party/FreeRTOS/Source/queue.c
		Middlewares/Third_Party/FreeRTOS/Source/tasks.c
		Middlewares/Third_Party/FreeRTOS/Source/timers.c
)

include_directories(Core/Inc)
include_directories(Core/Inc/display)
include_directories(Core/Inc/helpers)
include_directories(Core/Inc/app)
include_directories(Core/Inc/bsp)
include_directories(Core/Inc/menu)
include_directories(Core/Inc/profiles)
include_directories(Drivers/STM32F1xx_HAL_Driver/Inc)
include_directories(Drivers/STM32F1xx_HAL_Driver/Inc/Legacy)
include_directories(Middlewares/Third_Party/FreeRTOS/Source/include)
include_directories(Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS)
include_directories(Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM3)
include_directories(Drivers/CMSIS/Device/ST/STM32F1xx/Include)
include_directories(Drivers/CMSIS/Include)



set(LIST_OF_SOURCES
	        ${GROUP_CORE_SRC}
		${GROUP_DRIVERS_STM32F1XX_HAL_DRIVER_SRC}
		${GROUP_MIDDLEWARES_THIRD_PARTY_FREERTOS_SOURCE}
		${GROUP_MIDDLEWARES_THIRD_PARTY_FREERTOS_SOURCE_CMSIS_RTOS}
		${GROUP_MIDDLEWARES_THIRD_PARTY_FREERTOS_SOURCE_PORTABLE_GCC_ARM_CM3}
		${GROUP_CORE_SRC_DISPLAY}
		${GROUP_CORE_SRC_HELPERS}
		${GROUP_CORE_SRC_APP}
		${GROUP_CORE_SRC_BSP}
		${GROUP_CORE_SRC_MENU}
		${GROUP_CORE_SRC_PROFILES}
)
