SET(GROUP_SRC_SRC
	${CMAKE_CURRENT_LIST_DIR}/src/stm32f1xx_hal_conf.h
	${CMAKE_CURRENT_LIST_DIR}/src/stm32f1xx_hal_msp.c
	${CMAKE_CURRENT_LIST_DIR}/src/stm32f1xx_hal_timebase_tim.c
	${CMAKE_CURRENT_LIST_DIR}/src/stm32f1xx_it.c
	${CMAKE_CURRENT_LIST_DIR}/src/stm32f1xx_it.h
	${CMAKE_CURRENT_LIST_DIR}/src/system_stm32f1xx.c
) # of GROUP_SRC_SRC


SET(INCLUDE_DIRS_STM32F103_LIST
	${CMAKE_CURRENT_LIST_DIR}/src
	${CMAKE_CURRENT_LIST_DIR}/startup
) # of INCLUDE_DIRS_STM32F103_LIST

SET(STM32F103_SOURCES_LIST
	${GROUP_SRC_SRC}
) # of STM32F103_SOURCES_LIST