message(STATUS "Processing ${CMAKE_CURRENT_LIST_FILE}...")
SET(GROUP_COMPILER_SRC
	${CMAKE_CURRENT_LIST_DIR}/compiler_defs.h
) # of GROUP_COMPILER_SRC


SET(INCLUDE_DIRS_COMPILER_LIST
	${CMAKE_CURRENT_LIST_DIR}
) # of INCLUDE_DIRS_COMPILER_LIST

SET(COMPILER_SOURCES_LIST
	${GROUP_COMPILER_SRC}
) # of COMPILER_SOURCES_LIST