#!/bin/env python3
#
# Usage:
# git rev-parse --short=8 HEAD | xargs scripts/gen_info.py > buildinfo.h

import sys
from datetime import datetime
from datetime import timezone

#now = datetime.now().astimezone()
now = datetime.now(timezone.utc)
now_dt = now.strftime("%d-%b-%Y %H:%M:%S %Z")
year_now = now.strftime("%Y")

sha = "not provided"

if len(sys.argv) > 1:
	sha = sys.argv[1]

str = []
str.append("/*")
str.append("This is autogenerated header! Do not edit it!")
str.append("Build date and time: " + now_dt)
str.append("git commit hash: " + sha)
str.append("*/")
str.append("#define BUILD_DATE_TIME \"Build date and time: "+ now_dt + "\"")
str.append("#define GIT_HASH \"Git commit hash: "+ sha + "\"")
str.append("/* End of the file */")

for i in range (0, len(str)):
	print(str[i])
quit()
